name: Chat App CI-CD Pipeline

on:
  push:
    branches:
      - devops-learning

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Backend Docker Image
        run: docker build -t chat-backend ./backend

      - name: Build Frontend Docker Image
        run: docker build -t chat-frontend ./frontend

      - name: Run Containers (CD Step)
        run: |
          docker stop chat-backend || true
          docker stop chat-frontend || true

          docker rm chat-backend || true
          docker rm chat-frontend || true

          docker run -d -p 5000:5000 --name chat-backend chat-backend
          docker run -d -p 3000:3000 --name chat-frontend chat-frontend